### ISSUE TITLE
Intermittent failure when running truffle tests

### ISSUE THREAD

**Issue by area** [ethereumjs/testrpc#35] opened 2016-03-17 16:00 UTC
I have two very similar tests for a pair of contracts that, when run using `truffle`, one of them intermittently fails. I have a MWE at https://github.com/area/testrpc_bug_reproduce

The tests 'never' fail (I looped them for an hour with no failures) when using the python based `eth-testrpc`, which is why I'm reporting this as a bug in `testrpc` rather than `truffle`.

Everything I've seen points to there being some sort of race condition, unfortunately.

- Intermittent
- More attempts are required to fail on lower-powered machines where the tests take longer.

I have put the output when using `truffle test --verbose-rpc` at https://gist.github.com/area/82654cad5db14932c48f for a passing pair of tests and then a run where the intermittent test fails.

EDIT: I've realised that I have the order of the tests reversed in that gist. https://gist.github.com/area/e67899bc16f61468231f has the output from the tests in the same order as they appear in the repository.

**Comment by tcoulter** [comment] 2016-03-18 16:08
@area Awesome - thanks for this. I confirmed that I reproduced it. Looking into it now.

**Comment by area** [comment] 2016-03-21 11:53
Not sure if it's good or bad news, but I assume it'll help: I've just seen the same failure on a test written using the pattern of the 'never fails' test.

**Comment by tcoulter** [comment] 2016-03-21 16:51
I still haven't been able to pin this one down. Really tough issue; still looking.

**Comment by tcoulter** [comment] 2016-03-28 19:07
@area I can't get this to reproduce anymore. I was able to reproduce it earlier today, however, it no longer seems to be an issue.

Things I did between then and now that could possibly affect it: 

* Restarted my computer (gross, but possible)
* Removed my `node_modules` directory within the testrpc checkout and reinstalled.

I've narrowed it down to those two things (at least, that's all I can think of at the moment). There has also been some changes to master which I'm running now and, although they likely shouldn't have affected this bug, they could have.

Can you give it a try and see if you can reproduce? If so, try the above two things and let me know if the issue goes away (if it does, this isn't necessarily a good thing). I used to be able to reproduce it nearly 100% of the time after a few runs. Now the test seems to be looping forever.

**Comment by tcoulter** [comment] 2016-03-28 19:08
Oh, one last thing: I'm on the latest version of Truffle. Although I *hope* that's unrelated, still cannot be sure. https://github.com/ConsenSys/truffle/releases

**Comment by area** [comment] 2016-03-28 19:37
I can still reproduce on latest truffle, latest testrpc (after blowing away `node_modules`) and running the test immediately after restarting.

**Comment by tcoulter** [comment] 2016-03-29 14:59
Not sure what changed but I'm reproducing it steadily now.

**Comment by tcoulter** [comment] 2016-03-29 15:57
To follow up, I added a few log events to the root contract, and an address *is* getting created, as evidenced the outputs below. This suggests it's not an ethereumjs-vm issue, at least during contract creation. It might still be an issue during the call, but it's likely like it's an issue with the provider engine moreso ethereumjs-vm itself.

```
Events emitted during test:
    ---------------------------

    LogInteger(integer: 0)
    LogAddress(addr: 0x939a3b993dac23f66ff801de9955a58fda516bdb)
    LogInteger(integer: 1)

    ---------------------------
```

`createSubcontract()` now looks like this:

```
   function createSubcontract()
   {
     LogInteger(subcontractNum);
     address addr = address(new Subcontract());
     LogAddress(addr);

     subcontracts[subcontractNum] = addr;
     subcontractNum++;
     LogInteger(subcontractNum);
   }
```

**Comment by tcoulter** [comment] 2016-03-29 18:24
@area Can you give me access to your repository so I can commit changes to it? I've cut down the test case a bit to make things simpler, and I want to send this on to other people.

Here's what (I think) I've verified in the case where the test fails:

1. The root contract is created.
1. The root contract has code at its address, and its code matches that when the test passes.
1. The sub contract is created (address is output via logs, and checked via further requests done manually).
1. The sub contract has code at its address, and its code matches that when the test passes.
1. When the test passes, the root contract's `subcontractNum` is 1, as expected.
1. When the test fails, the root contract's `subcontractNum` is 0 when it should be 1. 
1. When the test passes, the root contract's `subcontracts` mapping has a value at index 0. 
1. When the test fails, the root contract's `subcontracts` mapping does not have a value at index 0. 
1. The test is sending the `createSubcontract()` transaction to the correct contract address (the root contract). 
1. The test is sending the `subcontractNum()` call to the correct address (the root contract; the same address the above transaction was sent to).
1. The TestRPC is requesting address storage from the same position whether or not the test passes or fails (i.e., the `eth_call` request results in a `eth_getStorageAt` request by the provider engine, and the parameters of that request are the same no matter if the test passes or fails). 

I've also added some code to the test that display some of this information, which I'll commit once given access. Here's a comparison between when the test passes and fails:

```
Using environment test.
Compiling contracts...


  Contract: RootContract

  RootContract address:                   0x5a6c643d09ec67eafe95adc2536582528472e259
  Creating SubContract...
    Sent to (via getTransactionByHash):   0x5a6c643d09ec67eafe95adc2536582528472e259
  SubContract address (via logs):         0x72cd343446b821c07e42397fbc5a368ff0cc1563
  SubContract address (via RootContract): 0x72cd343446b821c07e42397fbc5a368ff0cc1563
  SubContract count   (via RootContract): 1
  SubContract code:                       0x606060405200

    ✓ this test will eventually fail (659ms)


  1 passing (1s)

Using environment test.
Compiling contracts...


  Contract: RootContract

  RootContract address:                   0xeb848628bb5d70f83801e9a1d244989758170dd3
  Creating SubContract...
    Sent to (via getTransactionByHash):   0xeb848628bb5d70f83801e9a1d244989758170dd3
  SubContract address (via logs):         0xe166dc445d31108fe8358ac6c765e08107725afe
  SubContract address (via RootContract): 0x0000000000000000000000000000000000000000
  SubContract count   (via RootContract): 0
  SubContract code:                       0x606060405200

    1) this test will eventually fail

    Events emitted during test:
    ---------------------------

    LogAddress(addr: 0xe166dc445d31108fe8358ac6c765e08107725afe)
    LogInteger(integer: 1)

    ---------------------------


  0 passing (1s)
  1 failing
```

I'm still not able to account for the discrepancy and my hypotheses are minimal. Will continue.

**Comment by tcoulter** [comment] 2016-03-29 19:49
Update (here for posterity): Using the changes on my machine, which I hope to upload to the test repo, you can reproduce the error deterministically by starting the TestRPC with the following parameters:

```
$ ./bin/testrpc -m "fat family plate raw violin boring spread income swim ethics tenant liberty"

(and then in a different terminal)
$ while ../truffle/cli.js test; do :; done
```

For me, it fails on the first test run, and always fails.

As well, using a different mnemonic, you can have the first run pass but the second one fail, if you want to compare a passing then failing test:

```
$ ./bin/testrpc -m "rule time service awful dog bicycle rescue repair robot goose patrol target"

(and then in a different terminal)
$ while ../truffle/cli.js test; do :; done
```

It turns out the deterministic addresses created produce the erroneous behavior 100% of the time.

**Comment by tcoulter** [comment] 2016-03-29 21:17
Passing TestRPC output: https://gist.github.com/tcoulter/55384811f76a6e515363f55dbdfd1158
Failing TestRPC output: https://gist.github.com/tcoulter/f5395f1338924522e7904cdc43e74cb5

**Comment by tcoulter** [comment] 2016-03-29 21:28
Oh ***, the second `put` appears to be updating the root contract's state second time.

First:
```
> util.rlp.decode("0xf8448080a0b5e842349ccfe67678e039b67b31faff7ddbf183d6ad225c72609034e132813fa0d931bda081742df3cfb479e9320a8c0900a1f4954500f186d267c38c5f88113a")
[ <Buffer >,
  <Buffer >,
  <Buffer b5 e8 42 34 9c cf e6 76 78 e0 39 b6 7b 31 fa ff 7d db f1 83 d6 ad 22 5c 72 60 90 34 e1 32 81 3f>,
  <Buffer d9 31 bd a0 81 74 2d f3 cf b4 79 e9 32 0a 8c 09 00 a1 f4 95 45 00 f1 86 d2 67 c3 8c 5f 88 11 3a> ]
```

Second
```
> util.rlp.decode("0xf8440180a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0d931bda081742df3cfb479e9320a8c0900a1f4954500f186d267c38c5f88113a")
[ <Buffer 01>,
  <Buffer >,
  <Buffer 56 e8 1f 17 1b cc 55 a6 ff 83 45 e6 92 c0 f8 6e 5b 48 e0 1b 99 6c ad c0 01 62 2f b5 e3 63 b4 21>,
  <Buffer d9 31 bd a0 81 74 2d f3 cf b4 79 e9 32 0a 8c 09 00 a1 f4 95 45 00 f1 86 d2 67 c3 8c 5f 88 11 3a> ]
```

I've verified through some hacks that if I filter out the last `put`, the test passes successfully.

@wanderer This is definitely an error for you.

**Comment by tcoulter** [comment] 2016-03-30 00:02
Cause found, video here: https://youtu.be/tzjr_hTE_lg

This cache insertion is the culprit. What do we do? https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/cache.js#L80

**Comment by kumavis** [comment] 2016-03-30 01:41
damn @tcoulter fantastic sleuth work! the ethereumjs-vm has some funky behaviour with its caches that i tried to fix during my refactors over the summer, but required large changes that caused hundreds of breaking tests (there ares thousands or tens of thousands of tests). so that never got merged. Maybe we can try for a more minimal change that resolves this issue.

**Comment by area** [comment] 2016-03-30 09:09
Sorry didn't give you access to my repo last night, but I'm super glad to see progress. I'm now much more comfortable with the fact that I wasn't able to figure out what was happening myself after seeing how deep into the rabbit hole you had to go!

Hope a fix appears soon.

**Comment by tcoulter** [comment] 2016-03-30 16:41
Update: This PR fixes the issue: https://github.com/ethereumjs/ethereumjs-vm/pull/54. Let's hope the thousands of ethereumjs-vm tests pass ::cross your fingers::

**Comment by tcoulter** [comment] 2016-04-01 15:07
This has been fixed on master!

**Closed by tcoulter** 2016-04-01 15:07 UTC
